name: morty
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  animated_list_plus: ^0.5.2
  animated_snack_bar: ^0.4.0
  auto_animated: ^3.2.0
  flutter_local_notifications: ^17.2.2
  persistent_bottom_nav_bar: ^6.2.1
  auto_size_text: ^3.0.0
  awesome_bottom_bar: ^1.2.4
  bloc: ^8.1.4
  cached_memory_image: ^1.3.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.2.3
  collection: ^1.17.2
  cross_fade: ^0.3.1
  dart_date: ^1.3.2
  dartz: ^0.10.1
  dio: ^5.3.2
  easy_debounce: ^2.0.3
  easy_refresh: ^3.4.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  extended_tabs: ^4.1.0
  fade_indexed_stack: ^0.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.3.1
  flutter_image_stack: ^0.0.7
  flutter_keyboard_visibility: ^6.0.0

  flutter_native_splash: ^2.3.2
  flutter_rating_bar: ^4.0.1
  flutter_rounded_progress_bar: ^0.3.2
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.6
  font_awesome_flutter: ^10.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_gallery_saver: ^2.0.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  lottie: ^3.1.0
  mime: ^1.0.4
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  photo_manager: ^3.0.0-dev.5
  photo_manager_image_provider: ^2.1.0
  pinput: ^3.0.1
  readmore: ^2.2.0
  share_plus: ^8.0.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  social_share: ^2.3.1
  flutter_rating_stars: ^1.1.0
  stacked: ^3.4.1+1
  carousel_slider: ^5.0.0
  soundpool: ^2.4.1
  timelines: ^0.1.0
  timezone: ^0.9.2
  haptic_feedback: ^0.5.1+1
  transparent_image: ^2.0.1
  url_launcher: ^6.2.6
  uuid: ^4.1.0
  validatorless: ^1.2.3
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.1.4
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/


  fonts:
    - family: Montserrate
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
